'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const sodium = require('./load-sodium.cjs');
require('../crypto-core.js');
(async () => {
  await sodium.ready; const c = QuietChatCore.createCore(sodium);
  const alice = c.create('Alice test phrase 123456'), bob = c.create('Bob test phrase 123456');
  const bobID = c.saveContact(alice, 'Боб', c.view(bob).card, true);
  const aliceID = c.saveContact(bob, 'Алиса', c.view(alice).card, true);
  const text = 'Привет! 👋\nПереносы, кавычки " и символы <script> остаются текстом.';
  const first = c.encrypt(alice, bobID, text), second = c.encrypt(alice, bobID, text);
  assert.notEqual(first, second); assert.equal(c.decrypt(bob, first).text, text);
  assert.equal(c.decrypt(bob, first).duplicate, true);
  assert.equal(c.decrypt(alice, c.encrypt(bob, aliceID, 'Ответ')).text, 'Ответ');
  const envelope = JSON.parse(sodium.to_string(sodium.from_base64(first.slice(4))));
  const box = sodium.from_base64(envelope.box); box[box.length - 1] ^= 1;
  const tampered = 'QC1:' + sodium.to_base64(sodium.from_string(JSON.stringify({...envelope, box: sodium.to_base64(box)})));
  assert.throws(() => c.decrypt(bob, tampered), /подлинности/);
  assert.throws(() => c.decrypt(alice, first), /другому ключу/);
  assert.throws(() => c.saveContact(alice, 'Я', c.view(alice).card, true), /ваш ключ/);
  assert.throws(() => c.readCard(c.view(bob).card.slice(0, -1) + 'z'), /ошибка/);
  const zero = new Uint8Array(32);
  assert.throws(() => c.readCard('QCK1:' + sodium.to_base64(zero) + '.' + c.keyID(zero).slice(0, 12)), /нельзя использовать/);
  c.saveContact(alice, 'Боб', c.view(bob).card, false);
  assert.throws(() => c.encrypt(alice, bobID, text), /сверьте/);
  c.saveContact(alice, 'Боб', c.view(bob).card, true);
  assert.throws(() => c.encrypt(alice, bobID, 'а'.repeat(32769)), /64 КиБ/);
  assert.throws(() => c.create('short'), /12 символов/);
  const backup = c.exportProfile(alice);
  assert(!backup.includes(alice.document.private)); assert(!backup.includes('Боб'));
  const restored = c.open(backup, 'Alice test phrase 123456');
  assert.equal(c.view(restored).card, c.view(alice).card);
  assert.equal(c.decrypt(restored, c.encrypt(bob, aliceID, text)).text, text);
  assert.throws(() => c.open(backup, 'wrong password'), /Неверный пароль/);
  c.changePassword(restored, 'New test phrase 123456');
  const changed = c.exportProfile(restored);
  assert.equal(c.view(c.open(changed, 'New test phrase 123456')).card, c.view(alice).card);
  assert.throws(() => c.open(changed, 'Alice test phrase 123456'), /Неверный пароль/);
  assert.equal(c.view(c.open(backup, 'Alice test phrase 123456')).id, alice.id);
  if (process.argv[2]) {
    const fixture = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
    const mobile = c.open(fixture.backup, fixture.password);
    assert.equal(c.view(mobile).card, fixture.mobileCard);
    assert.equal(c.decrypt(mobile, fixture.fromPython).text, fixture.text);
    c.saveContact(mobile, 'Компьютер', fixture.pythonCard, true);
    fs.writeFileSync(process.argv[3], JSON.stringify({toPython: c.encrypt(mobile, fixture.pythonID, text), backup: c.exportProfile(mobile), text}));
    console.log('Python → JavaScript: public cards, Argon2id profile, authenticated message OK.');
  }
  c.destroy(alice); c.destroy(bob); c.destroy(restored);
  console.log('Crypto checks OK: round trip, unique nonce, tamper, routing, verification, invalid keys, limits, backup, passwords.');
})().catch(error => { console.error(error); process.exitCode = 1; });
